config/routes.rb
Rails.application.routes.draw do
  resources :artists do
    resources :songs, only: [:index, :show]
  end
  resources :songs
end

app/models/artist.rb
class Artist < ActiveRecord::Base
  has_many :songs
end

app/models/song.rb
class Song < ActiveRecord::Base
  belongs_to :artist

  def artist_name
    self.try(:artist).try(:name)
  end

  def artist_name=(name)
    artist = Artist.find_or_create_by(name: name)
    self.artist = artist
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def index
    @artists = Artist.all
  end

  def show
    @artist = Artist.find(params[:id])
  end

  def new
    @artist = Artist.new
  end

  def create
    @artist = Artist.new(artist_params)

    if @artist.save
      redirect_to @artist
    else
      render :new
    end
  end

  def edit
    @artist = Artist.find(params[:id])
  end

  def update
    @artist = Artist.find(params[:id])

    @artist.update(artist_params)

    if @artist.save
      redirect_to @artist
    else
      render :edit
    end
  end

  def destroy
    @artist = Artist.find(params[:id])
    @artist.destroy
    flash[:notice] = "Artist deleted."
    redirect_to artists_path
  end

  private

  def artist_params
    params.require(:artist).permit(:name)
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  def index
    if params[:artist_id]
      @artist = Artist.find_by(id: params[:artist_id])
      if @artist.nil?
        redirect_to artists_path, alert: "Artist not found"
      else
        @songs = @artist.songs
      end
    else
      @songs = Song.all
    end
  end

  def show
    if params[:artist_id]
      @artist = Artist.find_by(id: params[:artist_id])
      @song = @artist.songs.find_by(id: params[:id])
      if @song.nil?
        redirect_to artist_songs_path(@artist), alert: "Song not found"
      end
    else
      @song = Song.find(params[:id])
    end
  end

  def new
    @song = Song.new
  end

  def create
    @song = Song.new(song_params)

    if @song.save
      redirect_to @song
    else
      render :new
    end
  end

  def edit
    @song = Song.find(params[:id])
  end

  def update
    @song = Song.find(params[:id])

    @song.update(song_params)

    if @song.save
      redirect_to @song
    else
      render :edit
    end
  end

  def destroy
    @song = Song.find(params[:id])
    @song.destroy
    flash[:notice] = "Song deleted."
    redirect_to songs_path
  end

  private

  def song_params
    params.require(:song).permit(:title, :artist_name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
  def display_artist(song)
    song.artist.nil? ? link_to("Add Artist", edit_song_path(song)) : link_to(song.artist_name, artist_path(song.artist))
  end
end

app/helpers/songs_helper.rb
module SongsHelper

end

app/views/artists/edit.html.erb
<h1>Editing <%= @artist.name %></h1>

<%= form_for @artist  do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br />

  <%= f.submit %>
<% end %>

app/views/artists/index.html.erb
<h1>Artists</h1>
<ul>
  <% @artists.each do |artist| %>
    <li><%= link_to artist.name, artist_songs_path(artist) %></li>
  <% end %>
</ul>

app/views/artists/new.html.erb
<h1>Create an Artist</h1>

<%= form_for @artist  do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br />

  <%= f.submit %>
<% end %>

app/views/artists/show.html.erb
<h1><%= @artist.name %></h1>
<ul>
  <% @artist.songs.each do |song| %>
    <li><%= link_to song.title, artist_song_path(@artist, song) %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flatiron Tunes</title>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <% flash.each do |name, msg| -%>
      <%= content_tag :div, msg, class: name %>
    <% end -%>
    <%= yield %>
  </body>
</html>

app/views/songs/_form.html.erb
<%= form_for @song  do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %><br>
  <%= f.label :artist_name %>
  <%= f.text_field :artist_name %>
  <br />

  <%= f.submit %>
<% end %>

app/views/songs/edit.html.erb
<h1>Editing <%= @song.title %></h1>
<%= render partial: "form" %>

app/views/songs/index.html.erb
<ul>
<% @songs.each do |song| %>
  <li><%= display_artist(song) %> - <%= link_to song.title, song_path(song) %></li>
<% end %>
</ul>
<br>
<%= link_to "Add New Song", new_song_path %>

app/views/songs/new.html.erb
<h1>Create a Song</h1>
<%= render partial: "form" %>

app/views/songs/show.html.erb
<h1><%= link_to @song.title, song_path(@song) %></h1>
<h3> by <%= display_artist(@song) %></h3>

<%= link_to "All Songs", songs_path %>